services:
  caddy:
      image: caddy:2.11-alpine
      restart: unless-stopped
      ports:
        - "80:80"
        - "443:443"
        - "443:443/udp"
      volumes:
        - ./conf:/etc/caddy
        - caddy_data:/data
        - caddy_config:/config
  database:
    image: mariadb
    restart: always
    environment:
      MYSQL_DATABASE: panel
      MYSQL_USER: pterodactyl
      MYSQL_PASSWORD: pteropassword
      MYSQL_RANDOM_ROOT_PASSWORD: "yes"
    volumes:
      - db:/var/lib/mysql
  cache:
    image: redis
    restart: always
  php-fpm:
    build: ./panel-app/
    restart: always
    depends_on:
      - database
    volumes:
      - app:/var/www/html/
      - storage:/var/www/html/storage/
      - public:/var/www/html/public/
    environment:
      DB_HOST: database
      DB_PORT: 3306
      DB_DATABASE: panel
      DB_USERNAME: pterodactyl
      DB_PASSWORD: pteropassword

volumes:
  public:
  db:
  storage:
  app:
  caddy_data:
  caddy_config: